// Real-browser regression: SVG visibility, mouse dragging, and corrected capture.
// Node 22+, Python, and Chromium/Brave (override executable with BROWSER).
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {spawn} = require('node:child_process');
const root = path.resolve(__dirname, '..');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'book-be-gone-test-'));
const children = [];
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
async function until(fn) {
  for (let i = 0; i < 100; i++) { const result = await fn(); if (result) return result; await pause(100); }
  throw Error('Timed out waiting for browser or server');
}
function launch(command, args, options={}) {
  const child = spawn(command, args, options); children.push(child);
  child.on('error', error => { console.error(error.message); });
  return child;
}
let ws, reportFailure;
(async () => {
  const server = launch('python3', ['-u', 'tests/browser_server.py'],
    {cwd: root, env: {...process.env, BOOK_BE_GONE_DATA: path.join(temporary, 'data')}, stdio: ['ignore','pipe','pipe']});
  let output = ''; server.stdout.on('data', data => output += data);
  const port = await until(() => /^\d+\n/.test(output) && Number(output.trim()));
  const browser = process.env.BROWSER || '/opt/brave.com/brave/brave';
  launch(browser, ['--headless', '--no-sandbox', '--disable-gpu', '--no-first-run',
    '--no-default-browser-check', '--remote-debugging-port=0', '--window-size=1200,900',
    '--user-data-dir=' + path.join(temporary, 'browser'), 'about:blank'], {stdio:'ignore'});
  const activePort = path.join(temporary, 'browser', 'DevToolsActivePort');
  const debugPort = await until(() => fs.existsSync(activePort) && fs.readFileSync(activePort,'utf8').split('\n')[0]);
  const tabs = await (await fetch(`http://127.0.0.1:${debugPort}/json`)).json();
  ws = new WebSocket(tabs[0].webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { ws.onopen=resolve; ws.onerror=reject; });
  let id=0; const pending=new Map();
  ws.onmessage = e => {const message=JSON.parse(e.data);if(message.id){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(message.error):task.resolve(message.result)}};
  const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
  const evaluate=async expression=>{
    let timeout;const result=await Promise.race([send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true}),new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('Browser evaluation timed out: '+expression)),15000)})]).finally(()=>clearTimeout(timeout));
    if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));
    return result.result.value;
  };
  await send('Page.enable');
  // A deterministic gradient is the webcam source; app startup/capture remain real.
  await send('Page.addScriptToEvaluateOnNewDocument',{source:`
    window.fixture=document.createElement('canvas');fixture.width=640;fixture.height=480;
    const context=fixture.getContext('2d'), pixels=context.createImageData(640,480);
    for(let y=0;y<480;y++)for(let x=0;x<640;x++)pixels.data.set([x/3,y/2,80,255],(y*640+x)*4);
    context.putImageData(pixels,0,0);
    navigator.mediaDevices.getUserMedia=async()=>{const stream=fixture.captureStream(10);setInterval(()=>context.putImageData(pixels,0,0),100);return stream};
    navigator.mediaDevices.enumerateDevices=async()=>[];
  `});
  await send('Page.addScriptToEvaluateOnNewDocument',{source:`
    window.q=selector=>document.querySelector(selector);
    window.api=async(url,body)=>{const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const value=await r.json();if(!r.ok)throw Error(value.error);return value;};
    window.currentBook=()=>q('select[aria-label="Book"]').value;
  `});
  const errors=[];
  reportFailure=async()=>{console.error(await evaluate("document.body?.innerText.slice(-4000)"));console.error(JSON.stringify(errors));const shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('/tmp/book-be-gone-svelte-failure.png',Buffer.from(shot.data,'base64'));};
  await send('Runtime.enable');
  const oldMessage=ws.onmessage;
  ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);oldMessage(e);};
  const click=selector=>evaluate(`q(${JSON.stringify(selector)}).click()`);
  const button=text=>evaluate(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)}&&b.offsetParent!==null);if(!b)throw Error('Button not found: '+${JSON.stringify(text)});b.click()})()`);
  const fill=(selector,value)=>evaluate(`(()=>{const e=q(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const idle=()=>until(()=>evaluate("!q('.status-dot.working') && !q('.error')"));
  const stale=await send('Page.addScriptToEvaluateOnNewDocument',{source:`window.fetch=async()=>new Response(JSON.stringify({running:true,book:'old',page:'000046'}));`});
  await send('Page.navigate',{url:`http://127.0.0.1:${port}/`});
  await until(()=>evaluate("document.body?.textContent.includes('Server update needed')"));
  assert.equal(await evaluate("!!q('.app-shell')"),false);
  await send('Page.removeScriptToEvaluateOnNewDocument',{identifier:stale.identifier});
  await send('Page.reload');
  await until(()=>evaluate("!!q('.app-shell')"));
  await click('button[aria-label="New book"]');
  await fill('input[aria-label="New book title"]','Svelte book');
  await button('Create book');
  await until(()=>evaluate("!!q('.capture-workspace')"));
  await button('Start camera');
  await until(()=>evaluate("!!q('.corner-overlay') && q('video').videoWidth===640"));
  const corner=await evaluate("(()=>{const r=q('.corner-overlay').getBoundingClientRect();return {x:r.left+r.width*.05,y:r.top+r.height*.05,toX:r.left+r.width*.2,toY:r.top+r.height*.15}})()");
  for(const [type,x,y] of [['mousePressed',corner.x,corner.y],['mouseMoved',corner.toX,corner.toY],['mouseReleased',corner.toX,corner.toY]])await send('Input.dispatchMouseEvent',{type,x,y,button:'left',buttons:type==='mouseMoved'?1:undefined,clickCount:1});
  const corners=await evaluate("[...q('.corner-overlay').querySelectorAll('circle')].map(c=>[+c.getAttribute('cx'),+c.getAttribute('cy')])");
  assert.ok(Math.abs(corners[0][0]-200)<5);assert.equal(corners[0][1],corners[1][1]);
  await click('.capture-button');
  await until(()=>evaluate("q('.capture-footer').textContent.includes('1 captures')"));
  await click('.capture-button');
  await until(()=>evaluate("q('.capture-footer').textContent.includes('2 captures')"));
  await button('Read');
  await until(()=>evaluate("q('select[aria-label=\"Book page\"]').options.length===2"));
  await evaluate("q('.image-viewport img').decode()");
  assert.ok(await evaluate("q('.image-viewport img').naturalWidth<640"));
  await click('summary[aria-label="OCR settings"]');
  await fill('select[aria-label="OCR model"]','custom');
  await fill('input[aria-label="Custom OCR model identifier"]','test-vision-model');
  await fill('select[aria-label="Thinking level"]','high');
  assert.equal(await evaluate("localStorage.getItem('book-be-gone-effort')"),'high');
  await click('summary[aria-label="OCR settings"]');
  await fill('select[aria-label="Book page"]','000001:0');
  await click('summary[aria-label="More OCR actions"]');
  await button('OCR selected capture');
  await until(()=>evaluate("!!q('article[data-live=true] strong')"));
  assert.equal(await evaluate("q('article[data-live=true] strong').textContent"),'Bold');
  assert.equal((await evaluate("api('/api/status')")).effort,'high');
  assert.equal((await evaluate("api('/api/text/'+currentBook()+'/000001')")).pages.length,0);
  await until(()=>evaluate("q('select[aria-label=\"Book page\"]').options.length===3 && !q('.status-dot.working')"));
  await evaluate("q('article[data-key=\"000001:0\"] img').decode()");
  assert.ok(await evaluate("q('article[data-key=\"000001:0\"] img').naturalWidth>0"));
  await button('OCR remaining · 1');
  await until(()=>evaluate("q('.status-copy')?.textContent.includes('Capture 000002')"));
  await fill('select[aria-label="Book page"]','000001:0');
  await click('article[data-key="000001:0"] mark');
  await until(()=>evaluate("!!q('textarea')"));
  assert.equal(await evaluate("q('textarea').value.slice(q('textarea').selectionStart,q('textarea').selectionEnd)"),'[illegible]');
  await send('Input.insertText',{text:'restored word'});
  await pause(800);
  assert.match(await evaluate("q('textarea').value"),/restored word/);
  await button('Save');
  await until(()=>evaluate("!q('textarea')"));
  const record=await evaluate("api('/api/text/'+currentBook()+'/000001')");
  assert.match(record.pages[0].markdown,/restored word/);assert.match(record.pages[1].markdown,/\[illegible\]/);
  await until(()=>evaluate("!q('.status-dot.working') && q('select[aria-label=\"Book page\"]').options.length===4"));
  await fill('input[aria-label="Jump to printed page"]','45');
  await click('button[aria-label="Go to printed page"]');
  assert.equal(await evaluate("q('select[aria-label=\"Book page\"]').value"),'000001:1');
  await click('button[aria-label="Next page"]');
  await until(()=>evaluate("q('.image-viewport img').src.includes('/000002')"));
  await fill('select[aria-label="Book page"]','000001:0');
  await evaluate("q('.image-viewport img').decode()");
  await click('button[title="Actual size"]');
  await click('button[aria-label="Zoom in"]');await click('button[aria-label="Zoom in"]');await click('button[aria-label="Zoom in"]');
  assert.ok(await evaluate("q('.image-viewport img').width>q('.image-viewport img').naturalWidth"));
  const imageBox=await evaluate("(()=>{const r=q('.image-viewport').getBoundingClientRect();q('.image-viewport').scrollLeft=0;return {x:r.left+r.width*.7,y:r.top+r.height*.5}})()");
  await send('Input.dispatchMouseEvent',{type:'mousePressed',x:imageBox.x,y:imageBox.y,button:'left',clickCount:1});
  await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:imageBox.x-100,y:imageBox.y-40,button:'left',buttons:1});
  await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:imageBox.x-100,y:imageBox.y-40,button:'left',clickCount:1});
  assert.ok(await evaluate("q('.image-viewport').scrollLeft>0"));
  await button('Fit');
  await click('article[data-key="000001:0"] a[href*="page-000001-2"]');
  await until(()=>evaluate("q('select[aria-label=\"Book page\"]').value==='000001:1'"));
  await evaluate('history.back()');
  await until(()=>evaluate("q('select[aria-label=\"Book page\"]').value==='000001:0'"));
  // Figure crops use real Svelte-bound handles and keep text edits.
  const beforeFigure=(await evaluate("api('/api/text/'+currentBook()+'/000001')")).pages[0].figures[0];
  await button('Edit crop · 1');
  await until(()=>evaluate("!!q('dialog[open] .corner-overlay')"));
  const figureBox=await evaluate("(()=>{const r=q('dialog .corner-overlay').getBoundingClientRect();return {x:r.left+r.width*.2,y:r.top+r.height*.2,toX:r.left+r.width*.1,toY:r.top+r.height*.1}})()");
  for(const [type,x,y] of [['mousePressed',figureBox.x,figureBox.y],['mouseMoved',figureBox.toX,figureBox.toY],['mouseReleased',figureBox.toX,figureBox.toY]])await send('Input.dispatchMouseEvent',{type,x,y,button:'left',buttons:type==='mouseMoved'?1:undefined,clickCount:1});
  assert.ok(Math.abs(await evaluate("+q('dialog circle').getAttribute('cx')")-100)<10);
  await button('Save crop');
  await until(()=>evaluate("!q('dialog')"));
  const afterFigure=(await evaluate("api('/api/text/'+currentBook()+'/000001')")).pages[0];
  assert.notEqual(afterFigure.figures[0].asset,beforeFigure.asset);assert.match(afterFigure.markdown,/restored word/);
  // Saved-photo correction, preview, and revision protection remain available.
  await click('summary[aria-label="Image actions"]');await button('Crop & straighten');
  await until(()=>evaluate("!!q('dialog .corner-overlay')"));
  await button('Coordinates');
  await fill('input[aria-label="Corner 1 X percent"]','10');
  await fill('input[aria-label="Corner 1 Y percent"]','10');
  assert.equal(await evaluate("q('input[aria-label=\"Corner 2 Y percent\"]').value"),'10');
  await fill('input[aria-label="Page aspect ratio"]','0');
  await button('Preview');
  await until(()=>evaluate("!!q('dialog [role=alert]')"));
  await fill('input[aria-label="Page aspect ratio"]','1');
  await button('Preview');
  await until(()=>evaluate("!!q('.crop-result img')"));
  await button('Save crop');
  await until(()=>evaluate("!q('dialog')"));
  assert.ok((await evaluate("api('/api/book/'+currentBook())")).some(p=>!p.done));
  await button('Edit Markdown');
  await fill('textarea[aria-label="Edit page Markdown"]',afterFigure.markdown+'\n\nSee page 46.');
  await button('Preview');
  await until(()=>evaluate("!q('textarea') && q('.book-scroll').textContent.includes('See page 46.')"));
  await button('Save');
  await until(()=>evaluate("!q('.panelbar button.primary')"));
  await fill('select[aria-label="Book page"]','000002:0');
  await button('Edit Markdown');await click('.metadata summary');
  await fill('input[aria-label="Printed page number"]','46');
  await button('Save');await until(()=>evaluate("!q('textarea')"));
  await click('summary[aria-label="Book tools"]');await button('Link page references');
  await until(()=>evaluate("q('.notice')?.textContent.includes('Linked references')"));
  await fill('select[aria-label="Book page"]','000001:0');
  await click('article[data-key="000001:0"] a[href*="page-000002-1"]');
  await until(()=>evaluate("q('select[aria-label=\"Book page\"]').value==='000002:0'"));
  await evaluate('window.beforeReload=true');await send('Page.reload');
  await until(()=>evaluate("!window.beforeReload && q('select[aria-label=\"Book page\"]')?.value==='000002:0'"));
  assert.equal(await evaluate("localStorage.getItem('book-be-gone-model')"),'test-vision-model');
  await fill('select[aria-label="Book page"]','000001:0');
  const exported=await evaluate("(async()=>{const r=await fetch('/api/export/'+currentBook());return {ok:r.ok,type:r.headers.get('Content-Type'),size:(await r.blob()).size}})()");
  assert.equal(exported.ok,true);assert.equal(exported.type,'application/zip');assert.ok(exported.size>100);
  await evaluate('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
  // Scrolling selects the corresponding scan without redundant navigation.
  await evaluate("(()=>{const pane=q('.book-scroll'),next=q('article[data-key=\"000001:1\"]');pane.dispatchEvent(new WheelEvent('wheel'));pane.scrollTop+=next.getBoundingClientRect().top-pane.getBoundingClientRect().top+5;pane.dispatchEvent(new Event('scroll'))})()");
  await until(()=>evaluate("q('select[aria-label=\"Book page\"]').value==='000001:1'"));
  await fill('select[aria-label="Book page"]','000001:0');
  await pause(200);
  const screenshot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('/tmp/book-be-gone-svelte-desktop.png',Buffer.from(screenshot.data,'base64'));
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await pause(200);
  assert.ok(await evaluate('document.documentElement.scrollWidth<=window.innerWidth+1'),'Mobile layout must not overflow horizontally');
  const mobile=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('/tmp/book-be-gone-svelte-mobile.png',Buffer.from(mobile.data,'base64'));
  assert.deepEqual(errors,[],'No uncaught browser errors');
  console.log('PASS: Svelte capture, paired corners, live OCR, model/thinking, editing during OCR, navigation, zoom/pan, figure/page crops, references, bookmarks, export, and mobile layout');
})().catch(async error=>{console.error(error);if(reportFailure)await reportFailure().catch(()=>{});process.exitCode=1}).finally(async()=>{
  if(ws)ws.close();
  for(const child of children.reverse())child.kill('SIGTERM');
  await pause(500);
  fs.rmSync(temporary,{recursive:true,force:true,maxRetries:3,retryDelay:100});
});
